### PR TITLE
add UID to filenames

### PR DESCRIPTION
**Pull request by athulyaganesh**

### CODE REVIEW

**Comment by Jashgada** [comment]
Awesome! the send_request.php changes lgtm. Can you add some screenshots of your testings? like ss from the email along with file names to ensure that the changes work fine?

**Comment by Jashgada** [comment]
Also, were the changes in index.html and package-lock.json intentional?

**Comment by athulyaganesh** [comment]
Screenshot 2023-02-01 at 1 43 16 PM

**Comment by athulyaganesh** [comment]
Changes in package.lock and index.html were not intentional. Did not realize they were there.

**Review by Jashgada — APPROVED** [review]

**Pull request merged**
